language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.1.5
  - 2.2.0
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token: 6aa82237af30a07e040f64f0a184915522cdeead2da8df84b3a634bc9f189064
notifications:
  email:
    on_success: never
    on_failure: change